### ISSUE TITLE
add python3-jmespath dependency

### ISSUE THREAD

**Issue by sami-shakir** [nununo/ansible-role-proxmox-haos-install#30] opened 2022-12-14 13:33 UTC
I got the following error when running the role, so needs `python3-jmespath` apt package as a dependency

```
TASK [nununo.proxmox_haos_install : Determine relevant asset for latest release (json containing image name and url)] **************************
fatal: [proxmox1]: FAILED! => 
  msg: You need to install "jmespath" prior to running json_query filter
```

**Comment by nununo** [comment] 2023-01-08 01:15
Hello @sami-shakir,

I finally found some time to look at this issue.

This is not an issue with the role. Ansible needs it in the machine where it is running  (probably your local machine), not in the host being installed.

I'm using nix flakes to generate my development environment. In the improbable case that you're using nix flakes, here is is (you can see `pkgs.python310Packages.jmespath` mentioned there:

```nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};

        my-python-packages = python-packages: with python-packages; [
          pkgs.python310Packages.oci
          pkgs.python310Packages.jmespath
        ];

        python-with-my-packages = pkgs.python310.withPackages my-python-packages;
      in {
        devShell = pkgs.mkShell {
          nativeBuildInputs = [
            pkgs.ansible-lint
            pkgs.pre-commit
          ];
          buildInputs = [
            pkgs.ansible
            python-with-my-packages
          ];
        };
      });
}
```

 If not using nix flakes, you can probably solve this by running this command in your local machine:

```bash
pip3 install jmespath
```

Please let me know if this solved it.

Regards.

**Comment by nununo** [comment] 2023-11-03 19:52
Closing as this is not a bug and there was no reply.

**Closed as completed by nununo** 2023-11-03 19:52 UTC
Labels: question
